# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e8fe73c1046c86b8a5788fb16e4cd7a5e55c92eb3f619d432ae8c323e2a5a2f9544155c5455b12d2cac7267cb8c1d9cf10d5ec660a4787b0091d86c81ece51aa

test:
  secret_key_base: 94bef715405db85a0319d52e75add98e6d5b2138eae0425d48b05964c602b643d1cf3cca27b4fe20108a48aa3206847466dab055724016a29f44fca7171eee8c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
